import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className='flex justify-center items-center w-2/3 min-h-20 bg-green-400 mx-auto '>
        <div className='w-full'>
          <Nav />
        </div>
        </header>
        <main className="w-2/3 mx-auto h-screen flex justify-center items-center">
          {children}
        </main>

        <footer className='w-2/3 min-h-20 bg-black mx-auto'>
        </footer >
      </body>
    </html>
  );
}
